package state

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Markdown renders the Snapshot as the canonical STATE.md content.
// The timestamp line uses GeneratedAt, so two runs with the same Snapshot
// (same GeneratedAt) produce byte-identical output.
func (s *Snapshot) Markdown() string {
	var b strings.Builder

	// Header
	date := ""
	if len(s.GeneratedAt) >= 10 {
		date = s.GeneratedAt[:10]
	}
	fmt.Fprintf(&b, "<!-- Auto-generated by `docops state`. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "# Project State — %s\n\n", date)

	// Counts
	fmt.Fprintf(&b, "## Counts\n\n")
	c := s.Counts
	fmt.Fprintf(&b, "- Context: %d active · %d superseded\n", c.ContextActive, c.ContextSuperseded)
	fmt.Fprintf(&b, "- ADRs: %d accepted · %d draft · %d superseded (%d `coverage: required`, %d `coverage: not-needed`)\n",
		c.ADRAccepted, c.ADRDraft, c.ADRSuperseded, c.ADRCoverageRequired, c.ADRCoverageNotNeeded)
	fmt.Fprintf(&b, "- Tasks: %d backlog · %d active · %d blocked · %d done\n",
		c.TaskBacklog, c.TaskActive, c.TaskBlocked, c.TaskDone)
	b.WriteString("\n")

	// Needs attention
	fmt.Fprintf(&b, "## Needs attention\n\n")
	if len(s.NeedsAttention) == 0 {
		b.WriteString("- All clear.\n")
	} else {
		for _, a := range s.NeedsAttention {
			fmt.Fprintf(&b, "- %s\n", a.Message)
		}
	}
	b.WriteString("\n")

	// Active work
	fmt.Fprintf(&b, "## Active work\n\n")
	if len(s.ActiveWork) == 0 {
		b.WriteString("- (none)\n")
	} else {
		for _, t := range s.ActiveWork {
			meta := formatMeta(t.Assignee, t.Priority)
			req := ""
			if len(t.Requires) > 0 {
				req = " — requires: " + strings.Join(t.Requires, ", ")
			}
			if meta != "" {
				fmt.Fprintf(&b, "- %s (%s) %s%s\n", t.ID, meta, t.Title, req)
			} else {
				fmt.Fprintf(&b, "- %s %s%s\n", t.ID, t.Title, req)
			}
		}
	}
	b.WriteString("\n")

	// Recent activity
	fmt.Fprintf(&b, "## Recent activity\n\n")
	if len(s.RecentActivity) == 0 {
		b.WriteString("- (none)\n")
	} else {
		for _, e := range s.RecentActivity {
			if e.ShortSHA != "" {
				fmt.Fprintf(&b, "- %s %s %s\n", e.Date, e.ShortSHA, e.Subject)
			} else {
				fmt.Fprintf(&b, "- %s %s\n", e.Date, e.Subject)
			}
		}
	}
	b.WriteString("\n")

	// Recent amendments (ADR-0025) — only emit when present so projects
	// without amendments aren't bloated with empty sections.
	if len(s.RecentAmendments) > 0 {
		fmt.Fprintf(&b, "## Recent amendments\n\n")
		for _, a := range s.RecentAmendments {
			ref := ""
			if a.Ref != "" {
				ref = " (" + a.Ref + ")"
			}
			fmt.Fprintf(&b, "- %s %s [%s] %s — %s%s\n", a.Date, a.ADRID, a.Kind, a.Summary, a.By, ref)
		}
		b.WriteString("\n")
	}

	return b.String()
}

// formatMeta returns "assignee, priority", "assignee", "priority", or "" depending
// on which fields are non-empty.
func formatMeta(assignee, priority string) string {
	switch {
	case assignee != "" && priority != "":
		return assignee + ", " + priority
	case assignee != "":
		return assignee
	case priority != "":
		return priority
	}
	return ""
}

// JSON marshals the Snapshot as indented JSON.
func (s *Snapshot) JSON() ([]byte, error) {
	return json.MarshalIndent(s, "", "  ")
}
